apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: registry.cn-hangzhou.aliyuncs.com/tekton-pipelines/leeroy-web
      context: ../../../../leeroy-web
  tagPolicy:
    gitCommit: {}
#      variant: AbbrevCommitSha   # 使用缩写 git commit sha
deploy:
  kustomize:
    paths: ["../../../../kustomize/overlays/dev/leeroy-web"]

