apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: registry.cn-hangzhou.aliyuncs.com/tekton-pipelines/leeroy-app
      context: ../../../../leeroy-app
  tagPolicy:
    gitCommit: {}
#      variant: AbbrevCommitSha   # 使用缩写git commit sha
deploy:
  kustomize:
    paths: ["../../../../kustomize/overlays/dev/leeroy-app"]
